import axios, { AxiosError } from "axios";
import { onNavigate } from "@/actions/navigation";
import { getAccessToken, setAccessToken } from "../login-api/accessToken";

const apiUrl = process.env.NEXT_PUBLIC_API_URL;

export async function fetchAllAppointments(
  term: string,
  currentPage: number,
  sortBy: string,
  sortOrder: "ASC" | "DESC",
  filterStatus: string,
  startDate: string,
  endDate: string,
  router: any // Pass router instance as a parameter
): Promise<any> {
  const requestData = {
    term: term,
    page: currentPage,
    sortBy: sortBy,
    sortOrder: sortOrder,
    filterStatus: filterStatus,
    startDate: startDate,
    endDate: endDate,
  };
  try {
    console.log("searchPatient", requestData);
    const accessToken = getAccessToken();
    if (!accessToken) {
      throw new Error("Unauthorized Access");
    }

    const headers = {
      Authorization: `Bearer ${accessToken}`,
    };

    const response = await axios.post(
      `${apiUrl}/appointments/get/all`,
      requestData,
      { headers }
    );

    console.log(response.data);
    const { patientId, id, ...patientAppointmentsNoId } = response.data;
    console.log(patientAppointmentsNoId, "patient appointments after search");
    return patientAppointmentsNoId;
  } catch (error: any) {
    if (axios.isAxiosError(error)) {
      const axiosError = error as AxiosError;
      if (axiosError.message === "Network Error") {
        // Handle network error
        console.error("Connection refused or network error occurred.");
        return Promise.reject(
          new Error("Connection refused or network error occurred.")
        );
      }
      if (axiosError.response?.status === 401) {
        setAccessToken("");
        onNavigate(router, "/login");
        return Promise.reject(new Error("Unauthorized access"));
      }
    }
    console.error("Error searching patient list:", error.message);
    return Promise.reject(error);
  }
}
